
export const FULL_STATE_RESET = 'FULL_STATE_RESET';

export const ME_CHANGE = 'ME_CHANGE';
export const ME_RESET = 'ME_RESET';

export const MY_WORK_LOAD = 'MY_WORK_LOAD';
export const MY_WORK_LOAD_PENDING = 'MY_WORK_LOAD_PENDING';
export const MY_WORK_LOAD_FULFILLED = 'MY_WORK_LOAD_FULFILLED';
export const MY_WORK_LOAD_REJECTED = 'MY_WORK_LOAD_REJECTED';
export const MY_WORK_CHANGE = 'MY_WORK_CHANGE';
export const MY_WORK_RESET = 'MY_WORK_RESET';

export const TASK_LOAD = 'TASK_LOAD';
export const TASK_LOAD_PENDING = 'TASK_LOAD_PENDING';
export const TASK_LOAD_FULFILLED = 'TASK_LOAD_FULFILLED';
export const TASK_LOAD_REJECTED = 'TASK_LOAD_REJECTED';

export const TASK_UPDATE_STATUS = 'TASK_UPDATE_STATUS';
export const TASK_UPDATE_STATUS_FULFILLED = 'TASK_UPDATE_STATUS_FULFILLED';
export const TASK_UPDATE_STATUS_REJECTED = 'TASK_UPDATE_STATUS_REJECTED';

export const TASK_UPDATE_PRIORITY = 'TASK_UPDATE_PRIORITY';
export const TASK_UPDATE_PRIORITY_FULFILLED = 'TASK_UPDATE_PRIORITY_FULFILLED';
export const TASK_UPDATE_PRIORITY_REJECTED = 'TASK_UPDATE_PRIORITY_REJECTED';

export const TASK_UPDATE_SCHEDULE = 'TASK_UPDATE_SCHEDULE';
export const TASK_UPDATE_SCHEDULE_FULFILLED = 'TASK_UPDATE_SCHEDULE_FULFILLED';
export const TASK_UPDATE_SCHEDULE_REJECTED = 'TASK_UPDATE_SCHEDULE_REJECTED';

export const TASK_UPDATE_START_END = 'TASK_UPDATE_START_END';
export const TASK_UPDATE_START_END_FULFILLED = 'TASK_UPDATE_START_END_FULFILLED';
export const TASK_UPDATE_START_END_REJECTED = 'TASK_UPDATE_START_END_REJECTED';

export const TASK_UPDATE_DEADLINE = 'TASK_UPDATE_DEADLINE';
export const TASK_UPDATE_DEADLINE_FULFILLED = 'TASK_UPDATE_DEADLINE_FULFILLED';
export const TASK_UPDATE_DEADLINE_REJECTED = 'TASK_UPDATE_DEADLINE_REJECTED';

export const TASK_UPDATE_ESTIMATE = 'TASK_UPDATE_ESTIMATE';
export const TASK_UPDATE_ESTIMATE_FULFILLED = 'TASK_UPDATE_ESTIMATE_FULFILLED';
export const TASK_UPDATE_ESTIMATE_REJECTED = 'TASK_UPDATE_ESTIMATE_REJECTED';

export const TASK_UPDATE_PROGRESS = 'TASK_UPDATE_PROGRESS';
export const TASK_UPDATE_PROGRESS_FULFILLED = 'TASK_UPDATE_PROGRESS_FULFILLED';
export const TASK_UPDATE_PROGRESS_REJECTED = 'TASK_UPDATE_PROGRESS_REJECTED';

export const TASK_REPLY = 'TASK_REPLY';
export const TASK_REPLY_FULFILLED = 'TASK_REPLY_FULFILLED';
export const TASK_REPLY_REJECTED = 'TASK_REPLY_REJECTED';

export const TASK_UPDATE_AR_USER = 'TASK_UPDATE_AR_USER';
export const TASK_UPDATE_AR_USER_FULFILLED = 'TASK_UPDATE_AR_USER_FULFILLED';
export const TASK_UPDATE_AR_USER_REJECTED = 'TASK_UPDATE_AR_USER_REJECTED';

export const SEARCH = 'SEARCH';
export const SEARCH_PENDING = 'SEARCH_PENDING';
export const SEARCH_FULFILLED = 'SEARCH_FULFILLED';
export const SEARCH_REJECTED = 'SEARCH_REJECTED';
export const SEARCH_CLEAR = 'SEARCH_CLEAR';

export const FAVORITES_LOAD = 'FAVORITES_LOAD';
export const FAVORITES_LOAD_PENDING = 'FAVORITES_LOAD_PENDING';
export const FAVORITES_LOAD_FULFILLED = 'FAVORITES_LOAD_FULFILLED';
export const FAVORITES_LOAD_REJECTED = 'FAVORITES_LOAD_REJECTED';

export const PROJECT_TASKS_LOAD = 'PROJECT_TASKS_LOAD';
export const PROJECT_TASKS_LOAD_PENDING = 'PROJECT_TASKS_LOAD_PENDING';
export const PROJECT_TASKS_LOAD_FULFILLED = 'PROJECT_TASKS_LOAD_FULFILLED';
export const PROJECT_TASKS_LOAD_REJECTED = 'PROJECT_TASKS_LOAD_REJECTED';
export const PROJECT_TASKS_APPEND_NEW = 'PROJECT_TASKS_APPEND_NEW';

export const EVENTS_LOAD = 'EVENTS_LOAD';
export const EVENTS_LOAD_PENDING = 'EVENTS_LOAD_PENDING';
export const EVENTS_LOAD_FULFILLED = 'EVENTS_LOAD_FULFILLED';
export const EVENTS_LOAD_REJECTED = 'EVENTS_LOAD_REJECTED';

export const EVENT_LOAD = 'EVENT_LOAD';
export const EVENT_LOAD_PENDING = 'EVENT_LOAD_PENDING';
export const EVENT_LOAD_FULFILLED = 'EVENT_LOAD_FULFILLED';
export const EVENT_LOAD_REJECTED = 'EVENT_LOAD_REJECTED';

export const EVENT_UPDATE_STARTEND = 'EVENT_UPDATE_STARTEND';
export const EVENT_UPDATE_ACCOMPLISHED = 'EVENT_UPDATE_ACCOMPLISHED';
export const EVENT_UPDATE_ASSIGNED = 'EVENT_UPDATE_ASSIGNED';
export const EVENT_UPDATE_NOTES = 'EVENT_UPDATE_NOTES';

export const EVENT_DELETE = 'EVENT_DELETE';

export const ACTIVITY_STREAM_LOAD = 'ACTIVITY_STREAM_LOAD';
export const ACTIVITY_STREAM_LOAD_PENDING = 'ACTIVITY_STREAM_LOAD_PENDING';
export const ACTIVITY_STREAM_LOAD_FULFILLED = 'ACTIVITY_STREAM_LOAD_FULFILLED';
export const ACTIVITY_STREAM_LOAD_REJECTED = 'ACTIVITY_STREAM_LOAD_REJECTED';

export const ROOT_SCREEN_CHANGE = 'ROOT_SCREEN_CHANGE';

export const ADD_TIME_REPORT = 'ADD_TIME_REPORT';
export const ADD_TIME_REPORT_FULFILLED = 'ADD_TIME_REPORT_FULFILLED';
export const ADD_TIME_REPORT_REJECTED = 'ADD_TIME_REPORT_REJECTED';

export const TASK_CUSTOM_FIELDS = 'TASK_CUSTOM_FIELDS';
export const TASK_CUSTOM_FIELDS_FULFILLED = 'TASK_CUSTOM_FIELDS_FULFILLED';
export const TASK_CUSTOM_FIELDS_REJECTED = 'TASK_CUSTOM_FIELDS_REJECTED';

export const TASK_DELETE_MESSAGE = 'TASK_DELETE_MESSAGE';
export const TASK_DELETE_MESSAGE_FULFILLED = 'TASK_DELETE_MESSAGE_FULFILLED';
export const TASK_DELETE_MESSAGE_REJECTED = 'TASK_DELETE_MESSAGE_REJECTED';

export const TASK_UPDATE_MESSAGE = 'TASK_UPDATE_MESSAGE';
export const TASK_UPDATE_MESSAGE_FULFILLED = 'TASK_UPDATE_MESSAGE_FULFILLED';
export const TASK_UPDATE_MESSAGE_REJECTED = 'TASK_UPDATE_MESSAGE_REJECTED';

export const TASK_MOVE_TO_FOLDER = 'TASK_MOVE_TO_FOLDER';
export const TASK_MOVE_TO_FOLDER_FULFILLED = 'TASK_MOVE_TO_FOLDER_FULFILLED';
export const TASK_MOVE_TO_FOLDER_REJECTED = 'TASK_MOVE_TO_FOLDER_REJECTED';

export const TASK_RENAME = 'TASK_RENAME';
export const TASK_RENAME_FULFILLED = 'TASK_RENAME_FULFILLED';
export const TASK_RENAME_REJECTED = 'TASK_RENAME_REJECTED';

export const TASK_DELETE = 'TASK_DELETE';
export const TASK_DELETE_FULFILLED = 'TASK_DELETE_FULFILLED';
export const TASK_DELETE_REJECTED = 'TASK_DELETE_REJECTED';

export const TASK_UPLOAD_ATTACHMENT = 'TASK_UPLOAD_ATTACHMENT';
export const TASK_UPLOAD_ATTACHMENT_FULFILLED = 'TASK_UPLOAD_ATTACHMENT_FULFILLED';
export const TASK_UPLOAD_ATTACHMENT_REJECTED = 'TASK_UPLOAD_ATTACHMENT_REJECTED';

export const rootScreenValue = {
  login: 'login',
  my_work: 'my_work',
  project_tasks: 'project_tasks',
  activity_stream: 'activity_stream',
  events: 'events',
  favorites: 'favorites',
  search: 'search',
  task_create: 'task_create',
  settings: 'settings'
};
